name: cv
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - astroid=1.6.2=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.1.18=py36_0
  - cycler=0.10.0=py36hfc81398_0
  - freetype=2.8=h12048fb_1
  - intel-openmp=2018.0.0=h8158457_8
  - isort=4.3.4=py36_0
  - kiwisolver=1.0.1=py36h792292d_0
  - lazy-object-proxy=1.3.1=py36h2fbbe47_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1=hb4e282d_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.34=he12f830_0
  - matplotlib=2.2.2=py36ha7267d0_0
  - mccabe=0.6.1=py36hdaeb55d_0
  - mkl=2018.0.1=hfbd8650_4
  - more-itertools=4.1.0=py36_0
  - ncurses=6.0=hd04f020_2
  - numpy=1.14.2=py36ha9ae307_0
  - openssl=1.0.2o=h26aff7b_0
  - pip=9.0.1=py36_5
  - pylint=1.8.3=py36_0
  - pyparsing=2.2.0=py36hb281f35_0
  - python=3.6.4=hc167b69_3
  - python-dateutil=2.7.0=py36_0
  - pytz=2018.3=py36_0
  - readline=7.0=hc1231fa_4
  - scipy=1.0.0=py36h1de22e9_0
  - setuptools=38.5.1=py36_0
  - six=1.11.0=py36h0e22d5e_1
  - sqlite=3.22.0=h3efe00b_0
  - tk=8.6.7=h35a86e2_3
  - tornado=5.0=py36_0
  - wheel=0.30.0=py36h5eb2c71_1
  - wrapt=1.10.11=py36hc29e774_0
  - xz=5.2.3=h0278029_2
  - zlib=1.2.11=hf3cbc9b_2
  - pip:
    - opencv-contrib-python==3.4.0.12
prefix: /Users/Swapnil/anaconda3/envs/cv

